### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [Joh-Bo/f1-3-c2p1-colmar-academy#6]
Grade: Satisfactory

Summary: Nice job on this project, the final result looks good. Your mobile display also looks good. I see a lot of good techniques here, so you've clearly learned a lot. The biggest issue that I think could use improvement is naming convention. The names are too generic, and some of the selectors are just too complex. You have to remember that code is an ever changing thing, rarely do projects just sit static unchanging forever. Here is a link to one type of css naming convention and it also has links to others. Do a little research and see which on fits your style. http://getbem.com/introduction/
Overall really good job, hope you enjoyed the course.

**Comment by Joh-Bo** [comment]
Thanks for the review. I thought as well that my naming convention was too complex sometimes and as the project grows I could be lost myself. The documentation looks interesting, I will review it.
